/* ── Features Detail (3 Cards) ──────────────────────────────────────── */
const detailCards = [
  {
    bg: "bg-pink-50",
    iconBg: "bg-pink-100 text-pink-600",
    icon: "fas fa-comments",
    title: "AI Chat Assistant",
    desc: "Get instant, personalized academic support 24/7 for any subject. No more waiting for office hours.",
    linkColor: "text-pink-600 hover:text-pink-800",
    delay: "anim-delay-100",
  },
  {
    bg: "bg-yellow-50",
    iconBg: "bg-yellow-100 text-yellow-600",
    icon: "fas fa-stopwatch",
    title: "Exam Simulator",
    desc: "Practice under realistic, timed conditions to reduce exam anxiety and prepare for tests like WAEC and JAMB.",
    linkColor: "text-yellow-600 hover:text-yellow-800",
    delay: "anim-delay-200",
  },
  {
    bg: "bg-indigo-50",
    iconBg: "bg-indigo-100 text-indigo-600",
    icon: "fas fa-magic",
    title: "Magic Question Gen",
    desc: "Simply upload your study notes or textbook and instantly receive custom practice questions generated by AI.",
    linkColor: "text-indigo-600 hover:text-indigo-800",
    delay: "anim-delay-300",
  },
];

const FeaturesDetailSection = () => {
  return (
    <section className="py-24 bg-white relative">
      <div className="container mx-auto px-6 lg:px-12 text-center">
        <p className="fade-in-up text-purple-600 font-bold uppercase tracking-wider text-sm mb-3">
          Our Core Features
        </p>

        <h2 className="fade-in-up anim-delay-100 text-3xl md:text-5xl font-extrabold text-gray-900 leading-tight mb-6">
          Features That Empower Your{" "}
          <span className="relative inline-block px-2">
            <span className="relative z-10">Learning</span>
            <span className="absolute bottom-1 left-0 w-full h-3 bg-yellow-300 opacity-70 -z-10 transform -rotate-2" />
          </span>
        </h2>

        <p className="fade-in-up anim-delay-200 text-gray-500 text-lg max-w-2xl mx-auto mb-16">
          ULO AI is designed to solve major academic challenges by providing
          intelligent and accessible tools right on your mobile phone.
        </p>

        <div className="grid gap-8 md:grid-cols-3">
          {detailCards.map((card, i) => (
            <div
              key={i}
              className={`fade-in-up ${card.delay} group p-8 rounded-3xl shadow-lg hover:shadow-2xl bg-white border border-gray-100 transition-all duration-300 transform hover:-translate-y-2 text-center relative overflow-hidden`}
            >
              {/* Corner accent */}
              <div
                className={`absolute top-0 right-0 w-32 h-32 ${card.bg} rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110`}
              />

              <div className="relative z-10 flex justify-center mb-6">
                <div
                  className={`w-20 h-20 flex items-center justify-center rounded-2xl ${card.iconBg} shadow-inner`}
                >
                  <i className={`${card.icon} text-3xl`} />
                </div>
              </div>

              <h3 className="relative z-10 text-xl font-bold mb-3 text-gray-900">
                {card.title}
              </h3>
              <p className="relative z-10 text-gray-500 mb-6 leading-relaxed">
                {card.desc}
              </p>

              <a
                href="#"
                className={`relative z-10 inline-flex items-center font-bold transition ${card.linkColor}`}
              >
                Learn More
                <i className="fas fa-arrow-right ml-2 text-sm transform group-hover:translate-x-1 transition" />
              </a>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default FeaturesDetailSection;
